/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/cube.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/cube.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group name="pCube1" position={[0, 0, 0.02]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh name="Assembly-2" geometry={nodes['Assembly-2'].geometry} material={materials.standardSurface1} />
          </group>
          <group name="front" position={[0, -10.001, 0]} rotation={[Math.PI / 2, 0, 0]} />
          <group name="persp" position={[0.173, -0.144, 0.119]} rotation={[0.879, 0.746, 0.512]} />
          <group name="side" position={[10.001, 0, 0]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
          <group name="top" position={[0, 0, 10.001]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/cube.gltf')
